### ISSUE TITLE
does the code still work?

### ISSUE THREAD

**Issue by thomasdelaet** [jacobp100/node-gcm-ccs#4]
I tried to get this code to work but get a disconnect before being able to send messages.

Specifically, when I turn on DEBUG, I get the below output. So it connects to the google GCM servers but after sending authentication stanza and waiting a few seconds, the socket closes.

Any hints? Happy to fix things myself.

```
xmpp:connection setup stream +46ms
xmpp:connection send: <stream:stream xmlns="jabber:client"  xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="gcm.googleapis.com"> +58ms
xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="gcm.googleapis.com"> +91ms
xmpp:connection receive: <stream:stream from="gcm.googleapis.com" id="8080B6B5EA31CB44" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client"> +41ms
xmpp:connection receive: <stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms></stream:features> +4ms
xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">AUTHENTICATION-HERE</auth> +11ms
close event
```

**Comment by jacobp100** [comment]
What code are you using to connect?

**Comment by thomasdelaet** [comment]
<code>
var GCM = require("./node-gcm-ccs.js");

var projectId = process.env.PROJECT_ID;
var apiKey = process.env.API_KEY;

var gcm = new GCM(projectId, apiKey);

gcm.on('message', function(messageId, from, category, data) {
    console.log(messageId);
    console.log(from);
    console.log(category);
    console.log(data);
});

gcm.on('receipt', function(messageId, from, category, data) {
    console.log(messageId);
    console.log(from);
    console.log(category);
    console.log(data);
});

gcm.on('connected', function() {
    console.log("received connected event");
});

gcm.on("disconnected", function() {
    console.log("received disconnected event");
});

gcm.on("online", function() {
    console.log("received online event");
});

gcm.on("error", function() {
    console.log("received error event");
});

</code>

**Comment by thomasdelaet** [comment]
Hey Jacob

Thanks for your quick reply. I'm not sure what I'm doing wrong. Posted code above.

Thanks for any help!

**Comment by thomasdelaet** [comment]
One step further: It has to do with nodejs version. Works with 0.10.x, not with 0.12.x

**Comment by jacobp100** [comment]
I see. What OS are you running?

Do you have iojs handy, and if so, does it work on there?

**Comment by thomasdelaet** [comment]
I compiled iojs 2.5.0 from scratch but same problem as with node 0.12.0 and 0.12.7

OS: Debian/sid

**Comment by jacobp100** [comment]
It looks to be in https://github.com/node-xmpp/node-xmpp-client/issues/88

Edit: Looks it’s a dependency from the xmpp client (which in turn is a dependency). I won’t be able to fix it until they fix their dependency.

**Comment by thomasdelaet** [comment]
See also https://github.com/node-xmpp/node-xmpp/issues/275

Not yet fixed with new tree ...

**Comment by braindevils** [comment]
Thanks for fixing this if possible. Investigating to use this lib, but fails because of xmpp-dependency. Looking forward!

**Comment by jacobp100** [comment]
Should have probably kept more up-to-date with this. Is this still an issue?

**Comment by braindevils** [comment]
Hi,

Thanks for your response. I am still not able to get it to run. I may be
doing it wrong though. I copied the Example. I get:

/home/marijn/test/node_modules/node-gcm-ccs/node-gcm-ccs.js:30
var message = new xmpp.Element('message').c('gcm', { xmlns: 'google:mobile:
             ^
TypeError: undefined is not a function
    at _send
(/home/marijn/test/node_modules/node-gcm-ccs/node-gcm-ccs.js:30:18)
    at EventEmitter.send
(/home/marijn/test/node_modules/node-gcm-ccs/node-gcm-ccs.js:129:3)
    at Object.<anonymous> (/home/marijn/test/test.js:12:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by difitux** [comment]
Same issue here:

/xxx/node-gcm-ccs/node-gcm-ccs.js:30
                        var message = new xmpp.Element('message').c('gcm', { xmlns: 'google:mobile:
                                                 ^
TypeError: undefined is not a function
    at _send (/xxx/node-gcm-ccs/node-gcm-ccs.js:30:18)
    at EventEmitter.send (/xxx/node-gcm-ccs/node-gcm-ccs.js:129:3)
    at Object.<anonymous> (/xxx/server3.js:14:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Node.js version:
node -v
v0.12.7

**Comment by alemures** [comment]
@braindevils @difitux You just need to install the version in github with "npm install git+https://github.com/jacobp100/node-gcm-ccs.git" instead of use the npm version.

**Comment by difitux** [comment]
worked for me. Thank you!
